### ISSUE TITLE
Stop using deprecated UIWebView APIs

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-ios#106]
Apple says:

We identified one or more issues with a recent delivery for your app, "CoEpi.org" 0.1 (1). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by duskoo** [comment]
Seems that RXSwift (RxCocoa) is referencing UIWebVIew.
`LousyNetwork:CoEpi.app duskoo$ nm CoEpi|  grep -i uiweb
00000001002ee7ac T _$s7RxCocoa0A20WebViewDelegateProxyC03webD0ACSo05UIWebD0C_tcfC
00000001010e7320 S _$s7RxCocoa0A20WebViewDelegateProxyC03webD0ACSo05UIWebD0C_tcfCTq
00000001002ee860 T _$s7RxCocoa0A20WebViewDelegateProxyC03webD0ACSo05UIWebD0C_tcfc
00000001002ee668 T _$s7RxCocoa0A20WebViewDelegateProxyC03webD0So05UIWebD0CSgvM
00000001002ee710 t _$s7RxCocoa0A20WebViewDelegateProxyC03webD0So05UIWebD0CSgvM.resume.0
00000001010e7318 s _$s7RxCocoa0A20WebViewDelegateProxyC03webD0So05UIWebD0CSgvMTq
00000001002ee500 T _$s7RxCocoa0A20WebViewDelegateProxyC03webD0So05UIWebD0CSgvg
00000001010e7308 S _$s7RxCocoa0A20WebViewDelegateProxyC03webD0So05UIWebD0CSgvgTq
00000001002ee3f4 t _$s7RxCocoa0A20WebViewDelegateProxyC03webD0So05UIWebD0CSgvpACTK
00000001002ee468 t _$s7RxCocoa0A20WebViewDelegateProxyC03webD0So05UIWebD0CSgvpACTk
0000000101245dd8 S _$s7RxCocoa0A20WebViewDelegateProxyC03webD0So05UIWebD0CSgvpMV
00000001012d36a0 D _$s7RxCocoa0A20WebViewDelegateProxyC03webD0So05UIWebD0CSgvpWvd
00000001002ee3e8 T _$s7RxCocoa0A20WebViewDelegateProxyC03webD0So05UIWebD0CSgvpfi
00000001002ee594 T _$s7RxCocoa0A20WebViewDelegateProxyC03webD0So05UIWebD0CSgvs
00000001010e7310 s _$s7RxCocoa0A20WebViewDelegateProxyC03webD0So05UIWebD0CSgvsTq
00000001002eec4c T _$s7RxCocoa0A20WebViewDelegateProxyC12parentObject08delegateF0ACSo05UIWebD0C_xmtcAA0eF0CyAGSo0jdE0_pGRbzAA0eF4TypeRzSoAJ_p0E0RtzAG06ParentH0RtzlufC
00000001002eecb4 T _$s7RxCocoa0A20WebViewDelegateProxyC12parentObject08delegateF0ACSo05UIWebD0C_xmtcAA0eF0CyAGSo0jdE0_pGRbzAA0eF4TypeRzSoAJ_p0E0RtzAG06ParentH0Rtzlufc
00000001002eeb04 t _$s7RxCocoa0A20WebViewDelegateProxyC28registerKnownImplementationsyyFZACSo05UIWebD0CcfU_
000000010032f540 T _$s7RxSwift8ReactiveV0A5CocoaSo9UIWebViewCRbzlE11didFailLoadAA10ObservableCys5Error_pGvg
000000010032f694 t _$s7RxSwift8ReactiveV0A5CocoaSo9UIWebViewCRbzlE11didFailLoadAA10ObservableCys5Error_pGvgsAJ_pSayypGKcfU_
00000001010e7c20 S _$s7RxSwift8ReactiveV0A5CocoaSo9UIWebViewCRbzlE11didFailLoadAA10ObservableCys5Error_pGvpMV
000000010032f1e0 T _$s7RxSwift8ReactiveV0A5CocoaSo9UIWebViewCRbzlE12didStartLoadAA10ObservableCyytGvg
000000010032f328 t _$s7RxSwift8ReactiveV0A5CocoaSo9UIWebViewCRbzlE12didStartLoadAA10ObservableCyytGvgySayypGcfU_
00000001010e7c20 S _$s7RxSwift8ReactiveV0A5CocoaSo9UIWebViewCRbzlE12didStartLoadAA10ObservableCyytGvpMV
000000010032f390 T _$s7RxSwift8ReactiveV0A5CocoaSo9UIWebViewCRbzlE13didFinishLoadAA10ObservableCyytGvg
000000010032f4d8 t _$s7RxSwift8ReactiveV0A5CocoaSo9UIWebViewCRbzlE13didFinishLoadAA10ObservableCyytGvgySayypGcfU_
00000001010e7c20 S _$s7RxSwift8ReactiveV0A5CocoaSo9UIWebViewCRbzlE13didFinishLoadAA10ObservableCyytGvpMV
000000010032f138 T _$s7RxSwift8ReactiveV0A5CocoaSo9UIWebViewCRbzlE8delegateAD13DelegateProxyCyAFSo0efH0_pGvg
00000001010e7c20 S _$s7RxSwift8ReactiveV0A5CocoaSo9UIWebViewCRbzlE8delegateAD13DelegateProxyCyAFSo0efH0_pGvpMV
00000001002ef86c t _$sSo17UIWebViewDelegate_pSgWOh
00000001002eeb78 t _$sSo9UIWebViewC7RxCocoa0c3WebB13DelegateProxyCIeggo_AbEIegno_TR
00000001002eebd0 t _$sSo9UIWebViewC7RxCocoa0c3WebB13DelegateProxyCIeggo_AbEIegno_TRTA
00000001002ee234 t _$sSo9UIWebViewC7RxCocoa11HasDelegateA2cDP8delegate0F0QzSgvMTW
00000001002ee290 t _$sSo9UIWebViewC7RxCocoa11HasDelegateA2cDP8delegate0F0QzSgvMTW.resume.0
00000001002ee12c t _$sSo9UIWebViewC7RxCocoa11HasDelegateA2cDP8delegate0F0QzSgvgTW
00000001002ee1b8 t _$sSo9UIWebViewC7RxCocoa11HasDelegateA2cDP8delegate0F0QzSgvsTW
000000010115f254 s _$sSo9UIWebViewC7RxCocoa11HasDelegateACMA
00000001010e7290 S _$sSo9UIWebViewC7RxCocoa11HasDelegateACMc`
