### ISSUE TITLE
v0.1 Home Screen

### ISSUE THREAD

**Issue by duskoo** [Co-Epi/app-ios#11]
Home screen with navigation bar and 2 tappable cards

**Comment by rase-rocks** [comment]
Having the tappable elements fixed causes an issue on horizontal devices. Maybe this could be moved to a UICollectionView?

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-27 at 13 47 43](https://user-images.githubusercontent.com/38786434/77762651-c213b000-7031-11ea-9222-70647cd8f4b3.png)

**Comment by duskoo** [comment]
@rase-rocks Good point. I do think collectionView is a bit too much: I will embed the cards in scrollView instead.
