### ISSUE TITLE
Contact Alerts Visual bug

### ISSUE THREAD

**Issue by astewart43-gtri** [Co-Epi/app-ios#111]
When you have a list of new contact alerts, after tapping to select different alerts multiple times, eventually the text will become scrambled. 

**Screenshots**
![IMG_0002](https://user-images.githubusercontent.com/62766475/79262295-148d0300-7e5f-11ea-98af-27126b7cd5e3.PNG)

**Comment by astewart43-gtri** [comment]
I can no longer product this bug. Perhaps related to the refactoring of alerts when pull to refresh was added.

**Comment by i-schuetz** [comment]
The pull to refresh is just a subview of the table view and shouldn't affect this. I don't remember having done any other modifications to the layout.

**Comment by astewart43-gtri** [comment]
hmm, interesting. I will keep trying to reproduce the bug.

**Comment by astewart43-gtri** [comment]
This seems to be resolved, but I am unable to identify the commit that fixed it.
