### ISSUE TITLE
TCNCoalition package dependency graph issue

### ISSUE THREAD

**Issue by astewart43-gtri** [Co-Epi/app-ios#124]
When trying building develop, I get the following error:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/62766475/79930893-a674ad00-8417-11ea-9508-de68c033f4fa.png">
 In the "Swift Package Dependencies" list, tcn-client-ios is greyed out:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/62766475/79931007-e8055800-8417-11ea-8469-034319a6b641.png">

**Comment by duskoo** [comment]
@astewart43-gtri Which Xcode version are you using? See PR #122

**Comment by astewart43-gtri** [comment]
I am on 11.3. 
That is interesting...

**Comment by astewart43-gtri** [comment]
Switching to that branch resolved the TCN issue. 
I now have the below error:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/62766475/79992317-53374480-8481-11ea-912d-2315a5a611ba.png">

Will look into it and update this issue when I find a solution.

**Comment by i-schuetz** [comment]
https://github.com/Co-Epi/app-ios/pull/122 is approved. We should keep this open though until they release a new version. We shouldn't depend on develop.
