### ISSUE TITLE
Symptom reporting button "reports" when nothing is selected

### ISSUE THREAD

**Issue by Sam-gtri** [Co-Epi/app-ios#125]
**Describe the bug**
Submit button for symptoms reports even if nothing is selected - should be disabled unless a box has been ticked

**Comment by scottleibrand** [comment]
Let's hold off on fixing this: it's useful during the beta to be able to generate reports for testing without confusing anyone as to whether they're "real".

**Comment by scottleibrand** [comment]
Fixed in #127
