### ISSUE TITLE
Translate CoEpi into common languages

### ISSUE THREAD

**Issue by ericlavigne** [Co-Epi/app-ios#130]
Build on previous internationalization work (English/Spanish) to translate CoEpi into 8 other languages: German, French, Portuguese, Chinese (traditional/simplified), Korean, Russian, and Japanese.

**Comment by i-schuetz** [comment]
@danamlewis Do we have people that can proof read these translations?

**Comment by ericlavigne** [comment]
"Do we have people that can proof read these translations?"

I posted a proof reading request in the "general" slack channel on Thursday but received no responses. At this point my inclination is to release the translations as-is and wait for someone to complain. The text is easy to change later.
