### ISSUE TITLE
Error updating: error(message: "Couldn\'t parse response: ke ...

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-ios#138]
When I open Build 86 and go to Contact Alerts, it displays “Updating…” for awhile (maybe 30-60s) and then displays "Error updating: error(message: "Couldn\'t parse response: ke" (with the rest of the message cut off and not scrollable).

![image](https://user-images.githubusercontent.com/6982790/80316732-49c91780-87b4-11ea-96d6-0ceb9160d057.png)

**Comment by i-schuetz** [comment]
Fixed the layout.

**Comment by scottleibrand** [comment]
![image](https://user-images.githubusercontent.com/6982790/80318674-9155a080-87c0-11ea-8b73-b732023d01f4.png)

**Comment by scottleibrand** [comment]
Fixed as of build 94, probably via #154
