### ISSUE TITLE
New UX - symptom report screen

### ISSUE THREAD

**Issue by danamlewis** [Co-Epi/app-ios#145]
See Figma for details. 

![image](https://user-images.githubusercontent.com/7468165/80319675-91589f00-87c6-11ea-823f-b1c0402cf97a.png)

Note - may tweak the background rectangle 'texture' design, so can be built in the interim to focus on buttons etc.

**Comment by scottleibrand** [comment]
How do we intend for this UI to adapt to multiple screen and font sizes? Will it end up with a scroll bar? If so, we need to make sure we don't repeat https://github.com/Co-Epi/app-ios/issues/110 with it.
