### ISSUE TITLE
New UX - 4.1 shortness of breath follow up

### ISSUE THREAD

**Issue by danamlewis** [Co-Epi/app-ios#148]
See Figma for latest

![image](https://user-images.githubusercontent.com/7468165/80319863-be598180-87c7-11ea-80ea-65b7269b4e5c.png)

(circles will include graphic visuals)

**Comment by danamlewis** [comment]
@astewart43-gtri figma now has icons to pull in

**Comment by astewart43-gtri** [comment]
Great. Did we get an answer about what should be the intractable element?

**Comment by danamlewis** [comment]
@astewart43-gtri she said either (so both icon and text should be clickable, which I think we had defaulted to)

**Comment by i-schuetz** [comment]
Note: Should use table view. Same argumentation as in the [Android issue](https://github.com/Co-Epi/app-android/issues/118).

**Comment by astewart43-gtri** [comment]
completed and will be closed by new UX PR
