### ISSUE TITLE
Implement data model for new UX

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-ios#162]
Once the new UX screens are implemented, we need to implement a data model for storing their results and then wiring that up to the new v0.4 cloud API backend.

**Comment by astewart43-gtri** [comment]
work is in newUX-DataModel

**Comment by i-schuetz** [comment]
The idea here is to do a 1:1 port of Android. Ideally this should be in the Rust library.

**Comment by i-schuetz** [comment]
Let's split this in 2 parts and start with part 1:

1) Navigation flow: This is nearer to the UI, so not in the Rust lib. Should be mostly identical to: https://github.com/Co-Epi/app-android/blob/97d072e06870f141ff29d13e73f9641c8e4216f8/app/src/main/java/org/coepi/android/domain/symptomflow/SymptomFlow.kt (and related, e.g. `SymptomFlowManager`, `SymptomRouter`).

2) Data model: I'm not 100% sure yet, but it's possible that this will be in the Rust lib. This would be basically `SymptomInputs` and `SymptomInputsManager`.

The memo itself and the mapping from and to the api payload will be 100% in the Rust library.

**Comment by astewart43-gtri** [comment]
sounds good. I will make a separate branch (newUX-Navigation) to deal with the navigation flow. I plan to work on hooking up all the new UX screens to show as necessary. will leave the data model piece (branch newUX-DataModel) for now.

**Comment by i-schuetz** [comment]
Just want to reiterate the "identical": The code managing the flow should be a 1:1 port, as far as Swift allows (same structure, names, etc., while being idiomatic of course, but Kotlin is very similar so it shouldn't be difficult). This will ease possibly moving logic later to Rust. The code that's very near to the UI (view controllers, updating the navigation controller) of course has to be different. If you have any questions about the Android app, let me know!

**Comment by astewart43-gtri** [comment]
Thanks! Will likely follow up in slack later today.

**Comment by i-schuetz** [comment]
Addressed mostly in Rust library.
