### ISSUE TITLE
New UX - onboarding

### ISSUE THREAD

**Issue by danamlewis** [Co-Epi/app-ios#166]
see Figma for details

![image](https://user-images.githubusercontent.com/7468165/81245103-08611500-8fc9-11ea-9475-ed9b1a235029.png)

I want to tweak this text but Figma is using a font I don't have  so please tag me in the PR for these screens and I'll plan to edit it there.

**Comment by i-schuetz** [comment]
As a first step, let's use a fixed height for all the slides (the max possible).

**Comment by i-schuetz** [comment]
How does the transition between the slides look like?

**Comment by astewart43-gtri** [comment]
completed logic. small visual bug remains. can be dealt with after merging under a new tick as discussed in the backend meeting on 5/13/20.
