### ISSUE TITLE
New UX - exposure alert screen(s)

### ISSUE THREAD

**Issue by danamlewis** [Co-Epi/app-ios#175]
![image](https://user-images.githubusercontent.com/7468165/82512279-7414a900-9ac4-11ea-8a0a-d6a4d5f3d247.png)

see figma for details.

**Comment by i-schuetz** [comment]
@astewart43-gtri @Sam-gtri @aaruth3 Can you please give a status update? Who is working on this?

**Comment by Sam-gtri** [comment]
@i-schuetz I am working on this one

**Comment by danamlewis** [comment]
Suggested text for "What are exposure alerts?" page

Exposure alerts indicate that you have been in close proximity (e.g. within several feet) to another user with a mobile device running a compatible app. In CoEpi, an exposure alert will be generated if your device has logged a temporary contact number from the interaction, and that device's user later shares a symptom report that indicates the user may have been infectious during your proximity. 

Based on the symptom report in the exposure alert, and the time and date of likely exposure: you may decide to take no additional action; you may decide to more closely monitor yourself for symptoms in the few days following the date of the potential exposure; you may decide to self-isolate within your household to reduce the risk of transmitting to others; or you may decide to talk with a healthcare provider about your exposure.
