### ISSUE TITLE
Replace os_log?

### ISSUE THREAD

**Issue by i-schuetz** [Co-Epi/app-ios#179]
Opinions wanted: 

Advantages of os_log:
- Allow to use the system's console app, allowing people that's not using Xcode to run the app to see the logs (but: does anyone do this?)
- Console app has better UX (e.g. to filter logs) than Xcode's console.

Disadvantages:
- Complicated to use: It requires to import `os.log`, to use special placeholders for the variables to be readable, it doesn't allow string interpolation. To me it feels like a chore and I sometimes end just not adding logs.

- Can't be put in a wrapper: This may be surprising, but internals of the Swift language and how `os_log` is implemented make it impossible to abstract it, so we can't e.g. show the logs in the app like we do in the Android app. We also will not be able to enable cloud logging, should we want this in the future.

I'm in favor of removing it.

If we decide to do it, the plan would be to implement a logger, similar to [Android's](https://github.com/Co-Epi/app-android/blob/develop/app/src/main/java/org/coepi/android/system/log/Log.kt), that for now uses `print` internally and change all the `os_log` calls to use this logger.

**Comment by duskoo** [comment]
os_log is highly opinionated with focus on performance and privacy. It does not allow easy access to the persisted log files (which are in binary format). For this one must use the system diagnose feature of iOS (which I am not familiar with). We will definitely not be able to show the log entries in the app or upload them to a server (if that is what is meant by cloud logging).
They do offer a performance measurement functionality which will be useful for improving matching performance - using os signposts: see [RW article on Os_log](https://www.raywenderlich.com/605079-migrating-to-unified-logging-console-and-instruments) . We can go without it though.

Alternatives I have some experience with are:
[XCLogger](https://github.com/DaveWoodCom/XCGLogger)
[CocoaLumberJack](https://github.com/CocoaLumberjack/CocoaLumberjack)

@i-schuetz What do you mean by "cloud logging" exactly?

**Comment by i-schuetz** [comment]
@duskoo yes, with cloud logging I mean uploading the logs to a remote server. E.g. [SwiftyBeaver](https://github.com/SwiftyBeaver/SwiftyBeaver) has a platform for that. With a generic wrapper we'd be able to switch the logger or log to multiple places (e.g. print, the logs screen and the cloud).

Keep in mind that most of the critical code will be in Rust (including the matching). I'm planning at some point to set a callback in Rust to send the logs to Swift. We could probably use `os_log`, but the entire message would be always a public dynamic string. Not sure whether we still get anything of performance or privacy in this case.

It probably makes sense to postpone any actions here to 0.4 in any case, given that we've not properly tested the Rust library yet and this seems to be a deciding factor. Just collecting opinions for now.

**Comment by scottleibrand** [comment]
I'd be ok switching away from os_log, provided we have some other way to get logs with whichever other solution we replace it with.

**Comment by ivnsch** [comment]
It will be replaced for 0.3.

**Comment by ivnsch** [comment]
https://github.com/Co-Epi/app-ios/issues/237
