### ISSUE TITLE
NativeCore.swift is broken

### ISSUE THREAD

**Issue by ronenTG** [Co-Epi/app-ios#186]
I checked out the develop branch.
the following methods cannot be found:

`bootstrap_core(dbPath)`
`record_tcn(tcnStr)`
`fetch_new_reports()`
`set_symptom_ids(string)`
`set_cough_type(identifier)`
`set_cough_days(
            input.isSetInt,
            UInt32(input.toOptional()?.value ?? 0)
        )`
`set_cough_status(identifier)`
`set_breathlessness_cause(identifier)`
`set_fever_days(
            input.isSetInt,
            UInt32(input.toOptional()?.value ?? 0)
        )`
`set_fever_taken_temperature_today(
            input.isSetInt,
            input.boolInt
        )`
`set_fever_taken_temperature_spot(identifier)set_fever_highest_temperature_taken(
            input.isSetInt,
            input.toOptional()?.asFarenheit() ?? 0
        )`
`set_earliest_symptom_started_days_ago(
            input.isSetInt,
            UInt32(input.toOptional() ?? 0)
        )`
`submit_symptoms()`

**Comment by i-schuetz** [comment]
Did you run `Carthage bootstrap` (as specified in the readme)? These methods come from a native library, maintained [here](https://github.com/Co-Epi/app-backend-rust/releases).

**Comment by ronenTG** [comment]
Yes that's what i did. 
However, now that you've mentioned where these libraries come from, i realized the `Carthage bootstrap` command downloads the wrong version of app-backend-rust: `app-backend-rust at "0.1"`
I changed the `Cartfile.resolved` file from version 0.1 to 0.1.4

**Comment by duskoo** [comment]
> The bootstrap command will download and build the exact versions of your dependencies that are specified in Cartfile.resolved.

carthage update, on the other hand, would update the project to use the newest compatible versions of each dependency, which may not be desirable.

Source: https://www.raywenderlich.com/416-carthage-tutorial-getting-started

**Comment by i-schuetz** [comment]
Okay, the readme isn't incorrect, but we should explain updating too.

**Comment by duskoo** [comment]
Quick clarification:
@i-schuetz  carthage update will grab the latest lib release and that is ok during dynamic development. 
Ideally, we want each commit in iOS repo to reference corresponding lib release (to have correct version in Cartfile.resolved) as @ronenTG mentioned.
That way, if one needs to debug a particular app build, he can checkout the commit (which would contain correct lib version in Cartfile.resolved), run carthage bootstrap and get a working app...

**Comment by i-schuetz** [comment]
Ah - right. The problem is that when working with Rust, we update the dependency with a script, so the `Cartfile.resolved` file doesn't get updated. We should update it, of course.
