### ISSUE TITLE
Address Accessibility in App

### ISSUE THREAD

**Issue by mellowgeek** [Co-Epi/app-ios#189]
Look into what needs to happen to make the app accessible following [Apple best practices for iOS](https://developer.apple.com/accessibility/ios/)

**Comment by sthomas313-gatech** [comment]
https://medium.com/flawless-app-stories/swiftui-accessibility-e58d8850149f. - This might be some good resources for adding this to the application. I will do some more research on this. I am still figuring out the layout the code.

**Comment by ivnsch** [comment]
Note that we don't support SwiftUI. This was discussed at the beginning, but it ended being discarded, to make it possible to support iOS 12.

**Comment by sthomas313-gatech** [comment]
> Note that we don't support SwiftUI. This was discussed at the beginning, but it ended being discarded, to make it possible to support iOS 12.

Thank you Ian,  I had mistakenly thought those two were interchangeable, but Allen has explained to me the difference. I apologize for the confusion. I will reformat my research to swift-centered accessibility.

**Comment by sthomas313-gatech** [comment]
Features we should test for: Voice Over compatibility, Invert colors, increase contrast, reduce transparency, reduce motion, and Full keyboard access. Most of these can be checked by the Accessibility Inspector Tool in xCode for iOS. The voice over compatibility will require more in-depth look at the labels for all objects on every page in the app.

**Comment by sthomas313-gatech** [comment]
I have finished my check up of the app for accessibility features,  I will make a separate issue with all the issues. Will be closing this one.
