### ISSUE TITLE
Remove Roboto font

### ISSUE THREAD

**Issue by i-schuetz** [Co-Epi/app-ios#199]

**Comment by duskoo** [comment]
Slack comment might be about removing files from Figma, not from the app:
https://coepi.slack.com/archives/CUQGSQQ3A/p1590965002287500
Lets confirm before making the changes...

**Comment by i-schuetz** [comment]
See UX channel: https://coepi.slack.com/archives/CUR0KQRNG/p1590961570397400?thread_ts=1590750586.393800&cid=CUR0KQRNG
