### ISSUE TITLE
Improve layout on iPad / autolayout in general

### ISSUE THREAD

**Issue by i-schuetz** [Co-Epi/app-ios#202]
The UI is pretty much broken on iPad. It's probably not mandatory to optimize for iPad yet, but it should be passable.

**Comment by mellowgeek** [comment]
@i-schuetz Can we close this out with the updates that were made in the button background PRs? UI is much more consistent on the iPad now.

**Comment by ivnsch** [comment]
Yeah, I also added some fixes today (e.g. for the splash screen). It's looking better now.

I just noticed however some issues: The pressed button state (e.g. in "Today my cough was") has a different shape than the normal one.

Also, the "I don't know" / "Submit" buttons scale differently to the others. They should be consistent.

**Comment by i-schuetz** [comment]
Another point: The buttons in home should have a fixed height. On iPad they are occupying the entire screen which looks weird. On iPhone they also look a bit too large.
