### ISSUE TITLE
back button breaks at thank you screen

### ISSUE THREAD

**Issue by astewart43-gtri** [Co-Epi/app-ios#208]
if you navigate through the quiz to the thank you screen, hit the back button, and then submit the quiz again, the app crashes on line 55 of SymptomFlowManager.swift

**Comment by i-schuetz** [comment]
The back button in the thank you screen was [removed](48b4dae6822a09cb94042686c0458e9505c8365a). Is this not working?

**Comment by astewart43-gtri** [comment]
I just tested on develop, it has been removed there. I must have branched before this change.
