### ISSUE TITLE
Graceful handling of poorly formatted backend responses

### ISSUE THREAD

**Issue by LookItsJosh** [Co-Epi/app-ios#228]
This is a problem with the Android app, working on replicating the bug with the iOS version.  If already addressed please ignore.  If not, this may prevent security issues down the line.

For android: the app crashes if it receives an incorrectly formatted (non-base64 encoded) response from the backend. App should gracefully handle any corrupt or unexpected API responses without crashing

**Comment by ivnsch** [comment]
This was not an issue in iOS.
