### ISSUE TITLE
Red Exposure Circle/Text is not showing

### ISSUE THREAD

**Issue by Joshua-McCord** [Co-Epi/app-ios#262]
**Description**
When the user has exposure alerts, there is no notification displayed. This is includes the red dot and red text showing the number of alerts. 

**To Reproduce**
1. Get a new alert
2. Reload the page to show it
3. Navigate to home page

**Expected behavior**
There should be the red dot and text

**Comment by ivnsch** [comment]
Will be solved by https://github.com/Co-Epi/app-ios/issues/264
