### ISSUE TITLE
Exposure Alert Time Discrepency 

### ISSUE THREAD

**Issue by Joshua-McCord** [Co-Epi/app-ios#266]
**Describe the bug**
I reported symptoms on an Android Phone and reloaded the Exposure Alerts on iOS. The exposure alert should read June 11th, 11:00 AM, but the actual alert said June 10th 4:00 PM. 
The symptom was Breathlessness when "I stop for breath after walking about 100 yards..." (reported on Android, alerted for iOS). 

**To Reproduce**
1. Report Breathless Lvl. 2 on Android phone
2. Refresh iOS Exposure Alerts

**Expected behavior**
The time should have been 11:00 AM June 11th

**Additional context**
This has just been the worst time discrepancy. There are others, but this one has been the most extreme. Most others have been around ~5-30 min off.

**Comment by ivnsch** [comment]
Couldn't reproduce it. Can you confirm that you're looking at the reported time, not the contact time?

**Comment by Joshua-McCord** [comment]
It seems the reported time does say the correct time and date. Would the contact time not need to be the same as well? Or does the app remember when you were in contact and can lead to an exposure alert if the person records symptoms after the contact?

**Comment by ivnsch** [comment]
Yeah, that's the idea! The contact is the time when you were near to the person. The report will usually happen at a different time.

**Comment by Joshua-McCord** [comment]
Gotcha, I'll go ahead and close this!
