### ISSUE TITLE
Minor Housekeeping | Xcode Project | Point for discussion

### ISSUE THREAD

**Issue by rase-rocks** [Co-Epi/app-ios#27]
I think I'm not alone in finding that the `project.pbxproj` causes issues when merging.

Does anybody have any experience with:

[https://github.com/truebit/xUnique](https://github.com/truebit/xUnique)

It may take some of the headache away from merging. (Or maybe its just me!)

**Comment by i-schuetz** [comment]
Interesting, but it may create more problems than it solves. If we keep the PRs small and merge quickly (i.e. at most a couple of days) we shouldn't have that much problems with the `.pbxproj`
