### ISSUE TITLE
Fix alert OS notifications

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-ios#282]
It seems I forgot to integrate this with the new Rust core.

**Comment by woodsk97** [comment]
I'm not seeing exposure notifications on my iPhone -- is it because of this or should I open a new ticket?

**Comment by ivnsch** [comment]
You mean in notification center? Or the alerts in the app? If it's the later, yes open a new ticket.

**Comment by woodsk97** [comment]
I'm not getting notifications in the app - I'll open a ticket
