### ISSUE TITLE
Fever Symptom - Top bar is missing under follow up view for how you took your temperature

### ISSUE THREAD

**Issue by haleybear** [Co-Epi/app-ios#283]
**Describe the bug**
Currently once the user submits fever as a symptom the follow up screen for how they took their temperature does not have the title/comment of "Have you taken your temperature today?"

**To Reproduce**
1. Open App
2. Select Symptom Reporting
3. Select Fever
4. Select Submit
5. Input some number (I did 5) and select Submit on the screen 
6. Select Yes on the screen titled "Have you taken your temperature today"
7. Observe that the screen transitions and there are 4 options without context.

**Expected behavior**
Once the user selects "Yes" on the "Have you taken your temperature today" screen they should see this screen:
![image](https://user-images.githubusercontent.com/36253327/85406924-81440e00-b530-11ea-8fb5-df70a9ace57d.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/36253327/85407834-ba30b280-b531-11ea-9b5d-108d8ea7ed08.png)
**Additional context**
Phone type: iPhone8
0.3 Build 1

**Comment by sthomas313-gatech** [comment]
Sorry I saw the same issue on #290.
