### ISSUE TITLE
QUESTION: Should the Home Screen have a scroll bar?

### ISSUE THREAD

**Issue by haleybear** [Co-Epi/app-ios#284]
I have an iPhone 8 that I am using for testing and the main view of the home screen looked off until I realized that it was because there is a scroll bar for the two options. Is this supposed to happen on this screen?
![image](https://user-images.githubusercontent.com/36253327/85409090-5ad3a200-b533-11ea-99d4-382282986c6c.png)

**Comment by ivnsch** [comment]
Let's optimize this layout so it looks good on all screen sizes. A possibility would be a combination of the approaches that have been implemented so far: Aspect-ratio based cell height, but with a higher prio "smaller than" constraint for the height. This way on bigger screens (e.g. iPad) the cells don't take up nearly half of the screen's height.

Or ask UX.

**Comment by haleybear** [comment]
@i-schuetz that sounds fair, I noticed that one of the things that is helping the Android version is that the "Symptom Reporting" and "Exposure Alerts" text is on a single line, would that help here though?
![image](https://user-images.githubusercontent.com/36253327/85425967-dccdc600-b547-11ea-963a-24b47e35228d.png)

**Comment by ivnsch** [comment]
Not directly, as on iOS the cell's height is fixed currently. 

@Sam-gtri can you ask design what they want? It's btw important to keep in mind that we may have more than 2 items, in which case adjusting these 2 cells will not be very useful. But they may also say that for the foreseeable future it will be 2, in which case it's ok to optimize for it.

**Comment by Sam-gtri** [comment]
@i-schuetz  Who is in charge of design?

**Comment by ivnsch** [comment]
@Sam-gtri sorry! That should have been @astewart43-gtri (I'd ask in the UX channel).
