### ISSUE TITLE
Minor inconsistencies in Onboarding between FIgma, iOS and Android

### ISSUE THREAD

**Issue by woodsk97** [Co-Epi/app-ios#287]
I've noticed the following wording inconsistencies between iOS & Android during onboarding:

Bluetooth:
iOS:         Asks if Bluetooth can be used or not
Android:  Asks if Bluetooth can used all the time, while App is running, or not at all

Link for privacy information
Figma:     How is my data used?
iOS:         How is my data used?
Android:  How ill my data be used?

Header for 4th screen:
Figma:    Collaborate. Inform. Protect.
iOS:        Collaborate. Share. Protect.
Android: Collaborate. Inform. Protect.

iOS version:  Downloaded code this morning, built and installed.
Android version:  77

**Comment by astewart43-gtri** [comment]
@i-schuetz, do we want to alter the behavior of bluetooth on iOS? it seems that we want it all the time.

**Comment by astewart43-gtri** [comment]
I am about to make a PR to address the header for 4th screen

**Comment by ivnsch** [comment]
> @i-schuetz, do we want to alter the behavior of bluetooth on iOS? it seems that we want it all the time.

The permission models on iOS and Android are different and there's nothing we can do about that. We can refine the iOS handling, which is already being addressed in https://github.com/Co-Epi/app-ios/issues/279.

**Comment by astewart43-gtri** [comment]
great. closing this issue.
