### ISSUE TITLE
Exposure notifications not displaying in the app

### ISSUE THREAD

**Issue by woodsk97** [Co-Epi/app-ios#289]
Exposure alerts displayed in the app.  

I have two phones, Galaxy S10 and iPhone XR both running CoEpi.  According to the debug information, the phones see each other's TCN.   I've set symptoms on the Android.  From the debug log on the iPhone it looks like there are matches, however, there are no exposures displayed in the app.
![image](https://user-images.githubusercontent.com/67012738/85787550-91f3b000-b6f9-11ea-9792-58e4281a2529.png)

![image](https://user-images.githubusercontent.com/67012738/85787591-a0da6280-b6f9-11ea-98ce-77b609f06c52.png)

**Comment by ivnsch** [comment]
With this kind of issues it would be helpful to copy the log's text (to e.g. copy paste the report). You can do this by long-tapping the logs screen.

**Comment by ivnsch** [comment]
It seems that the parsing of the alerts was broken recently with the linter improvements (though I asked explicitly to disable it for this). After fixing it I'm able to see alerts (created with an Android device) again.

I wonder though if it's the same issue. I got an error message in the log and on the top of the alerts screen. Can you try again?

**Comment by SSNimnicht** [comment]
Piling on with logs I copied from my iPhone 7 with commit 2c22c3.  My iPhone is also not receiving any of my Android device exposure alerts in the app.  Note error fetching alerts message at 1355 in log.
[Logs_06302020.txt](https://github.com/Co-Epi/app-ios/files/4854090/Logs_06302020.txt)

**Comment by ivnsch** [comment]
> 1:55pm E Error fetching alerts: error(message: "Lib error result: LibResult<Array<NativeAlert>>(status: 502, data: nil, errorMessage: Optional(\"Invalid library result: decoding(\\\"Wasn\\\\\\\'t able to decode user input: To Some: keyNotFound(CodableKeys(stringValue: \\\\\\\"some\\\\\\\", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: \\\\\\\"data\\\\\\\", intValue: nil), _JSONKey(stringValue: \\\\\\\"Index 0\\\\\\\", intValue: 0), CodingKeys(stringValue: \\\\\\\"report\\\\\\\", intValue: nil), CodingKeys(stringValue: \\\\\\\"earliest_symptom_time\\\\\\\", intValue: nil)], debugDescription: \\\\\\\"No value associated with key CodableKeys(stringValue: \\\\\\\\\\\\\\\"some\\\\\\\\\\\\\\\", intValue: nil) (\\\\\\\\\\\\\\\"some\\\\\\\\\\\\\\\").\\\\\\\", underlyingError: nil)), To None: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: \\\\\\\"data\\\\\\\", intValue: nil), _JSONKey(stringValue: \\\\\\\"Index 0\\\\\\\", intValue: 0), CodingKeys(stringValue: \\\\\\\"report\\\\\\\", intValue: nil), CodingKeys(stringValue: \\\\\\\"earliest_symptom_time\\\\\\\", intValue: nil)], debugDescription: \\\\\\\"Expected to decode String but found a dictionary instead.\\\\\\\", underlyingError: nil))\\\")\"))")

**Comment by ivnsch** [comment]
Okay, this one is when you fill the earliest symptom time. Should be fixed now.
