### ISSUE TITLE
Commit fe95470 Won't Open

### ISSUE THREAD

**Issue by SSNimnicht** [Co-Epi/app-ios#297]
**Describe the bug**
I pulled down commit fe95470 onto my iPhone 7 and it won't open.  It built successfully in Xcode with several warnings, it installed on my phone and every time I select the app it just doesn't open. 

**To Reproduce**
1. Install commit fe95470.
2. Attempt to open the application.  It won't.

**Expected behavior**
The application should open and function.

**Comment by ivnsch** [comment]
Can you update develop and try again? Thanks!

These kind of issues would be caught by a working CI... 🙂

**Comment by woodsk97** [comment]
I just downloaded, when I run 'Carthage bootstrap' I get 'Illegal instruction: 4'

**Comment by woodsk97** [comment]
I did a carthage upgrade & it is now working - I was able to build, download, and open the app

**Comment by ivnsch** [comment]
Hmm it _should_ not be related with using `update` vs `bootstrap`, as the core version is [correctly specified](https://github.com/Co-Epi/app-ios/blob/develop/Cartfile.resolved#L2) (and there's not a newer one that `update` could be fetching). Maybe you cleaned the project or something?

**Comment by ivnsch** [comment]
Closing this either way, as it seems to be fixed. Feel free to comment.

**Comment by ivnsch** [comment]
> and there's not a newer one that update could be fetching

this is not true anymore. Just uploaded one.
