### ISSUE TITLE
Display Commit Hash for Currently Installed SW in Debug Log-iOS

### ISSUE THREAD

**Issue by SSNimnicht** [Co-Epi/app-ios#302]
**Is your feature request related to a problem? Please describe.**
When cloning the current iOS repository into xCode and then pushing from xCode to my iPhone device, the real version is not displayed at the bottom [Something like 0.3 (1) displays which is NOT accurate.].  

**Describe the solution you'd like**
It would be nice to have the commit hash in the debug log just for double checking purposes while testing and logging questions, comments and issues.

**Comment by ivnsch** [comment]
Displaying the commit hash in the local builds is not possible, because the app doesn't have knowledge of git. Even if it accessed it via api, it wouldn't know which commit you checked out. I also don't see the need for this. You should be able to check easily on the computer which commit you've checked out.

**Comment by duskoo** [comment]
Something like this might work: https://stackoverflow.com/questions/26514866/how-can-i-include-the-git-commit-hash-in-xcode

**Comment by ivnsch** [comment]
Wording improvement: Not (easily) possible without making assumptions about the local environment. And I don't see the point. Don't want to have to write & maintain custom scripts or requiring devs to install `PlistBuddy` to run the app, for a feature with unclear benefits.

Edit: It seems that `PlistBuddy` is installed by default in Apple platforms. Still, it's an additional dependency and I'm not convinced about the usefulness of this feature for local builds. And we don't have `PlistBuddy` necessarily for Android, where the feature is also requested.

**Comment by i-schuetz** [comment]
And before I get a new clarification, 
> install
is not accurate. The script seems to be installed by default in Apple platforms, but it's not in `PATH`, so it's either way an additional step configuring the project.

**Comment by ivnsch** [comment]
Or am I missing a use case where it makes sense? Maybe @SSNimnicht can explain? It may make sense if you go testing with the local build outside and want to submit an issue before coming back to the computer, or something? Or maybe working with multiple git clones?

**Comment by SSNimnicht** [comment]
@i-schuetz The specific use case I was documenting was when I have pushed the application onto an iPhone and am using the phone (not the emulator) to test the application (mainly from a bluetooth perspective).  Unlike the Android application where I get App Center installation notifications and can push the apk onto my phone (and thereby see the version info), when I pull the iOS application code into Xcode and then onto the phone the phone always displays the same version information even though I'm (fairly) sure I have a newer app on my iPhone.  See picture below.

![Unchanged_Version_Values](https://user-images.githubusercontent.com/67011880/86268007-8be84e00-bb95-11ea-8179-73380d3eb948.jpg)

**Comment by ivnsch** [comment]
As I said, in this case you can just look up the commit hash on the computer? I assume an installed git client, since you cloned the repo.

If you're using the built-in git client in Xcode, you can see the git status in the source control navigator: https://i.stack.imgur.com/2MJjQ.png

**Comment by SSNimnicht** [comment]
Fair enough

**Comment by ivnsch** [comment]
Though actually I just thought of a valid use case. When copying the logs (long tap), we attach the app version. Attaching the commit hash would be convenient for testers using develop / Xcode. But let's see if we still need it, since the current "testers using develop" are gone and we've AppCenter again.
