### ISSUE TITLE
Exposure alerts

### ISSUE THREAD

**Issue by haskinselena** [Co-Epi/app-ios#311]
**Individual exposure alerts**
1. Timeline of repeated interactions previously logged
2. Distance from you on exposure alert
3. Menu button in header to delete

<img width="845" alt="Screen Shot 2020-07-21 at 6 08 03 PM" src="https://user-images.githubusercontent.com/67452742/88112149-42c86000-cb7d-11ea-8148-0f41b54f1e72.png">

**Exposure alert screen** 

1. Red dots to indicate new alert - will disappear once clicked
2. Preview of first symptoms will show (similar to a text)
3. Blue boxed indicator to represent if an interaction is repeated (the user has already interacted with the same  person previously)
4. Definition of exposure alerts under title

<img width="424" alt="Screen Shot 2020-07-21 at 7 48 37 PM" src="https://user-images.githubusercontent.com/67452742/88118290-3945f480-cb8b-11ea-9826-908efff4cfd2.png">

**Comment by ivnsch** [comment]
@Co-Epi/ux just to confirm, was it decided at the end to add the calendar and links between exposures for 0.4?

**Comment by haskinselena** [comment]
No calendar, but if there are linked exposures we want the indicator to pop up and have the timeline of past exposures on the individual alert

**Comment by ivnsch** [comment]
@Co-Epi/ux re: "Previous exposures with this person": Is it intended to show only previous ones, or do we want to just show the others?

**Comment by haskinselena** [comment]
On the exposure alert page, all exposures (even those with the same person) are intended to show. If there are multiple encounters with the same person, an indicator "repeated interaction" will pop up, users will be able to click on that to get the normal information AND a timeline of previous exposures with the same person

**Comment by ivnsch** [comment]
@haskinselena Just to clarify re: "previously": I'm assuming that we don't want only _previous_ interactions, but _all (other)_ interactions with the same user. We may be seeing one of the "older" alerts, in which case we want to display the more recent interactions as well (correct me if I'm wrong).

**Comment by haskinselena** [comment]
Ah yes - that's correct!
