### ISSUE TITLE
500 nil error message displayed in exposure alerts

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-ios#351]
![63B3AE2B-D98A-4186-93C0-D62DEEA8BEFC](https://user-images.githubusercontent.com/6982790/89476363-5825b880-d73f-11ea-941e-2b7f1d67e255.jpeg)

**Comment by ivnsch** [comment]
Can't reproduce it. Is it possible to provide a description?

**Comment by scottleibrand** [comment]
It occurs every time I open the Exposure Alerts screen. Looks like these
are the corresponding logs.






----------
On Thu, Aug 6, 2020 at 3:53 AM, "Ivan Schütz" <notifications@github.com>
wrote:

Can't reproduce it. Is it possible to provide a description?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Co-Epi/app-ios/issues/351#issuecomment-669857744>, or
unsubscribe

**Comment by scottleibrand** [comment]
It occurs every time I open the Exposure Alerts screen. Looks like these are the corresponding logs.

![FCE2C1FE-65F3-4C31-9223-95F9B6F91F0C](https://user-images.githubusercontent.com/6982790/89558528-2e18d880-d7c9-11ea-90bf-7df97df591be.jpeg)

**Comment by ivnsch** [comment]
That's because the database migrations are not merged yet. It should work if you re-install the app.

**Comment by scottleibrand** [comment]
Gotcha. Reinstall fixed it. Thanks.
