### ISSUE TITLE
Repeat push notification on every Exposure Alert refresh

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-ios#353]
I've had a single exposure since reinstalling CoEpi 0.4, but now every time it refreshes the report list, either via schedule or on pull-to-refresh, it gives me a new iOS notification for the same exposure.

**Comment by duskoo** [comment]
@scottleibrand Proposed fix: send notification only if there is at least one unread alert retrieved from core (DB).
Android behaves the same as iOS. If proposed fix is accepted, I will make a PR for Android as well.

**Comment by scottleibrand** [comment]
This should be a lot better than the current behavior, so I’ve merged it for testing.
