### ISSUE TITLE
Distance debug logs are too noisy

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-ios#354]
The debug logs are currently unusable if another iOS device is in range, as the logs report new distance estimations multiple times per second, changing the position of the existing logs and making it impossible to find, read, or screenshot anything.

**Comment by duskoo** [comment]
PR #360  uses reactive operators
[groupBy](http://reactivex.io/documentation/operators/groupby.html)
and
[throttle/debounce](http://reactivex.io/documentation/operators/debounce.html) 
to:

1. split incoming tcn events (from BTooth layer) according to tcn value
2. throttle each tcn specific stream by taking one value every 5 sec
