### ISSUE TITLE
Make symptoms list contents more visible. 

### ISSUE THREAD

**Issue by astewart43-gtri** [Co-Epi/app-ios#36]
**Problem.**
If you did not know that the symptoms were a scrolling list, all but the 8 Plus give no indication that there is more to the list. See the picture below:

<img width="1861" alt="image" src="https://user-images.githubusercontent.com/62766475/77971437-a708a080-72bc-11ea-84ce-dbe467a267e9.png">

**Describe the solution**
A solution would be to flash the scroll bar when the page loads to show users that it is not a static list (https://developer.apple.com/documentation/uikit/uiscrollview/1619435-flashscrollindicators).

**Alternatives**
A suitable alternative would be to remove the scrolling all together in favor of a static list that we test on each device.

**Comment by scottleibrand** [comment]
If this takes any significant work to fix, we can defer it until after v0.1, when we'll likely be moving to a multi-page symptoms interview.

**Comment by astewart43-gtri** [comment]
If the plan is to move to a different model for the quiz, I don't think this is worth investing any time in.
