### ISSUE TITLE
Device Orientation Problems

### ISSUE THREAD

**Issue by astewart43-gtri** [Co-Epi/app-ios#37]
**Description**
Many of the UI elements are broken if the device is turned to landscape. See screenshots below:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/62766475/77974435-1f735f80-72c5-11ea-802b-00e462169406.png">

<img width="702" alt="image" src="https://user-images.githubusercontent.com/62766475/77974449-2b5f2180-72c5-11ea-8cb2-8ebd5eccae5e.png">

**To Reproduce**
In simulator:

- In menu bar select Hardware > Rotate Left/Right

On hardware:

- Turn off rotation lock in control center

- Rotate iPhone

**Resolution**
I see no reason that we can not simply disable Landscape mode all together. This is done here by unchecking the landscape boxes:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/62766475/77974941-8e9d8380-72c6-11ea-96ec-d1042675d516.png">

**Comment by i-schuetz** [comment]
IMO we definitely should lock to portrait. There's no reason to invest efforts in an app like this to support landscape mode (near/mid future at least).
