### ISSUE TITLE
Debug page causes crash app in alamofire-networking branch

### ISSUE THREAD

**Issue by astewart43-gtri** [Co-Epi/app-ios#42]
**Describe the bug**
When clicking to open the debug menu, the app crashes. The breakpoint is shown below.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/62766475/78102110-7e190600-73b7-11ea-8242-e204c3518db2.png">

**Comment by duskoo** [comment]
@astewart43-gtri Based on screenshot, RxSwift may be included in the project twice. Check your SPD dependencies and your Podfile.lock

**Comment by astewart43-gtri** [comment]
Yes, when that screenshot was taken, I believe I had it duplicated in the pod file. I reverted that commit, but I still have the error.

**Comment by duskoo** [comment]
Did you run:
pod install
after removing the line from the Podfile?

**Comment by astewart43-gtri** [comment]
Yes. It seems that RxAlamofire is the problem. Adding just it breaks the debug window.

**Comment by duskoo** [comment]
When you ad RxAlamoFire via Podfile, Cocoapods will install RxSwift and Alamofire pods as well (because those are dependencies for RxAlamofire). Cocoapods is not aware that RxSwift and Alamofire have already bee added as SPM packages... and you get a package collision.

**Comment by astewart43-gtri** [comment]
that makes sense. Is there a way to get around that?

**Comment by duskoo** [comment]
I would suggest that you use SPM as default package manager. All dependencies should be installed using SPM, except AppCenter lib (which requires Cocoapods).
Also, make sure you get the correct versions as stated in [RxAlamofire.podspec|https://github.com/RxSwiftCommunity/RxAlamofire/blob/master/RxAlamofire.podspec]
```
 ss.dependency "RxSwift", "~> 5.0"
 ss.dependency "Alamofire", "~> 4.8"
```
