### ISSUE TITLE
Display version/build number

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-ios#65]
We should display the version number, build number, and/or git commit on the home or debug screen so we can be sure which version someone is running when testing.

**Comment by duskoo** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-04-04 at 23 38 07](https://user-images.githubusercontent.com/4785666/78461951-ac575800-76cd-11ea-84f3-2238e548d401.png)

**Comment by scottleibrand** [comment]
Looks great, thanks.
