### ISSUE TITLE
How does CoreBluetooth works on iOS, in background?

### ISSUE THREAD

**Issue by TheRhullian** [Co-Epi/app-ios#78]
Hi, 

I want to ask if is possible to scan devices around, including Android, and detect, without connecting, those peripherals and after detecting, just exchange data. 

I want to build an app that wakes up just to scan e exchange data, without connecting both.

I tested your app and i saw that, the scan works only if the service UUID is unique, and you force the scan search for that same one, correct?

Thank you,
Rhullian Damião

**Comment by ivnsch** [comment]
This seems a general BLE question, and not very clearly formulated, so closing.
