### ISSUE TITLE
Transition to v0.3 backend

### ISSUE THREAD

**Issue by astewart43-gtri** [Co-Epi/app-ios#79]

**Comment by astewart43-gtri** [comment]
URL: https://q69c4m2myb.execute-api.us-west-2.amazonaws.com/v3/

**Comment by astewart43-gtri** [comment]
@duskoo is testing in branch: CoEpiNetworkingV3Tests

**Comment by i-schuetz** [comment]
The url was already updated on dev (for both iOS and Android), and posting a report is working (returns 200).

**Comment by astewart43-gtri** [comment]
@i-schuetz Great! 
What else needs to be done or tested?

**Comment by danamlewis** [comment]
@astewart43-gtri any status updates on this? should this be updated to reflect 0.4 (and therefore close https://github.com/Co-Epi/app-ios/issues/91 if it's a duplicate - or are these completely separate steps to migrate?)?

**Comment by astewart43-gtri** [comment]
If I understood the discussions Wednesday evening, this is now a duplicate. That v0.3 has been "renamed" to v0.4 Is that correct?

**Comment by scottleibrand** [comment]
Closing in favor of #91
