### ISSUE TITLE
Add Progress  indicator

### ISSUE THREAD

**Issue by duskoo** [Co-Epi/app-ios#81]
(see Android implementation)

Should be reusable, integrated with Rx.
Currently displayed during fetching alerts (matching) and submitting a report.

**Comment by duskoo** [comment]
This looks promising: http://rx-marin.com/post/rxswift-custom-bindings/

**Comment by i-schuetz** [comment]
Yep, we're already using rx bindings for the notifications (see `UIViewController+Rx`). `UIBindingObserver` is from older RxSwift versions (I question though this particular usage, as the notifications don't need the view controller. But we can revisit this later. For the progress indicator it does makes sense).

**Comment by i-schuetz** [comment]
Why is this marked as invalid, btw? Will we not use a progress indicator when submitting the reports?

**Comment by duskoo** [comment]
I understood we should put the progress indicator issue on hold, so 

> Why is this marked as invalid, btw? Will we not use a progress indicator when submitting the reports?

I understood we are putting progress indicator feature on hold... 
I will remove the labels.

**Comment by scottleibrand** [comment]
Per conversation with @i-schuetz, our current thinking is this would just be an "indefinite progress indicator": a spinning circle that indicates we're doing something, not a progress bar.
