### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-ios#92]
If the app detects an exposure match in the background, issue a notification.

**Comment by astewart43-gtri** [comment]
Background notification have been added. However, tapping the notification brings the user to the home screen of the app. a link to the alerts page still needs to be added.

**Comment by astewart43-gtri** [comment]
Notifications still need to be issued when the app is in the foreground. Perhaps something similar to the successful symptom report notifications?

**Comment by i-schuetz** [comment]
Maybe badges? Adding a small bubble with "new" (or similar) on the top right corner of the alerts item in home and the individual alerts in the alerts view?

**Comment by scottleibrand** [comment]
The notification pops up whether the app is foregrounded or backgrounded, and tapping it takes the user to the contacts alert screen. This is good enough for the current UI/UX: we can open a new issue for further enhancements. Thanks!
