### ISSUE TITLE
App icon badge 

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-ios#93]
Place the number of unacknowledged exposure matches as a red badge on the app icon.

**Comment by duskoo** [comment]
https://stackoverflow.com/a/54006948

**Comment by astewart43-gtri** [comment]
This has been added to update when the alert page is loaded in PR 113. However it still needs to be dynamically updated whenever the contact alerts are finished being processed.

**Comment by astewart43-gtri** [comment]
Currently, the behavior is to show to number of unseen alerts( as added in PR 113). Once the alerts view is loaded, the badge resets. Does this need to be changed to show the number of unacknowledged?

**Comment by scottleibrand** [comment]
I actually think I prefer the current behavior.

**Comment by astewart43-gtri** [comment]
so can this issue be closed?

**Comment by scottleibrand** [comment]
Hearing no objections, yes.
