### ISSUE TITLE
Symptom timing

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-ios#94]
Once users select symptoms, prompt them to pick a date when each of the selected symptoms started.

**Comment by duskoo** [comment]
@scottleibrand How should this look like? Sounds like a major change in UI/UX

**Comment by astewart43-gtri** [comment]
Was the intent to have a "number of days" page for each symptom? or is the pages asking about having "any" symptoms sufficient?

**Comment by astewart43-gtri** [comment]
As discussed in the call, closing for now. May reopen later if we decide we need a time for each symptom.
