### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by ericlavigne** [Co-Epi/app-ios#95]
Prepare for translation to other languages, starting with Spanish as an example.

https://developer.apple.com/internationalization/

**Comment by ericlavigne** [comment]
Translated some of the .swift files using Localizable.strings files.

Branch: Internationalization

**Comment by i-schuetz** [comment]
Looking good! Can you please also look into [SwiftGen](https://github.com/SwiftGen/SwiftGen)? It generates enums for the keys, which is safer and we get autocompletion.

**Comment by ericlavigne** [comment]
Yes, I'll check out SwiftGen.

In the current approach, I think the .swift translations are easy enough to deal with due to explicit keys, but the .xib translations involve random keys that are unreadable. If SwiftGen has a better option for .xib translation, that would be very welcome.

**Comment by i-schuetz** [comment]
I personally prefer to do the translations always in code. This way they in the same place and with SwiftGen it's very handy. When we transition to SwiftUI we'll need to have them in code anyway.

**Comment by ericlavigne** [comment]
"I personally prefer to do the translations always in code."

That sounds like a good plan. Thanks.

**Comment by ericlavigne** [comment]
All translations are now defined in Localizable.strings and applied in code. This already looks much nicer. I'll try SwiftGen next.

I applied symptom name translations within the "repo" code rather than in the UI. Are these names stored or sent over the network, so that using translated names might cause problems?

**Comment by i-schuetz** [comment]
Currently they're just local. It's fine to translate directly in the repo. The idea is to remove this if/when the backend sends the symptoms (which would be already translated).

**Comment by ericlavigne** [comment]
@i-schuetz The code for this issue is ready for review: https://github.com/Co-Epi/app-ios/pull/123
